name: Maven CI/CD

on:
 push:
    branches: 
    - main
    - mine
 workflow_dispatch:
  

jobs:
  build_and_test:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: zulu
        
    - name: Show Java version
      run: 'Java -version'

    - name: Checkout code
      uses: actions/checkout@v3
      with:
       ref: mine
       
    - name: Show Directory
      run: 'mvn compile'

    - name: SInstall Dependencies
      run: 'pwd'      

    - name: Build aplication
      run: 'mvn package -DskipTests'

    - name: Test aplication
      run: 'mvn test'
      
